=== jay417jay/AnalyticsTest/Packages/Beckhoff.TwinCAT.HMI.Analytics.ControlsExtension.1.35.91/runtimes/win-x64/net472/TcHmiAnalytics.Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "contentPermissionItemList": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Content Permission Item List",
      "type": "array",
      "items": {
        "$ref": "#/definitions/contentPermissionEntry"
      }
    },
    "contentPermissionEntry": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Content Permission Entry",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "page": {
          "type": "string"
        },
        "accessRight": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "accessright": {
                "type": "string"
              },
              "group": {
                "type": "string"
              },
              "permission": {
                "type": "string"
              },
              "internalPermission": {
                "type": "integer"
              }
            }
          }
        },
        "children": {
          "allOf": [
            { "default": [] },

            {
              "$ref": "#/definitions/contentPermissionItemList"
            }
          ]
        }
      }
    },
    "axisList": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Axis List",
      "type": "array",
      "items": {
        "$ref": "#/definitions/axisOptions"
      }
    },
    "axisOptions": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Options of an Axis Element",
      "type": "object",
      "properties": {
        "Label": {
          "type": "string"
        }
      }
    },
    "timeIntervalOptions": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Options of a time interval",
      "type": "object",
      "properties": {
        "Value": {
          "$ref": "tchmi:general#/definitions/TimeSpan"
        },
        "Unit": {
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "KeyValueStore": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "userID": {
            "type": "string"
          },
          "keyValueEntries": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "default": {}
    },
    "LayoutPropertiesKeyValueStore": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "layoutID": {
            "type": "string"
          },
          "keyValueEntries": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "default": {}
    },
    "LayoutStore": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "LayoutID": {
            "type": "string"
          },
          "LayoutValue": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "cS": {
                  "type": "integer"
                },
                "cE": {
                  "type": "integer"
                },
                "rS": {
                  "type": "integer"
                },
                "rE": {
                  "type": "integer"
                },
                "vis": {
                  "type": "boolean"
                }
              }
            }
          },
          "LayoutHash": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "CType": {
                  "type": "string"
                },
                "Cnt": {
                  "type": "integer"
                }
              }
            }
          },
          "InteractiveControls": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "CType": {
                  "type": "string"
                },
                "CId": {
                  "type": "string"
                }
              }
            }
          }
        },
        "required": [ "LayoutID", "LayoutValue", "LayoutHash" ]
      },
      "default": {}
    },
    "UserLayoutStore": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "UserLayoutID": {
            "type": "string"
          },
          "LayoutID": {
            "type": "string"
          },
          "UserID": {
            "type": "string"
          },
          "ContentID": {
            "type": "string"
          },
          "DisplayMode": {
            "type": "string"
          }
        },
        "required": [ "UserLayoutID", "LayoutID", "UserID", "ContentID", "DisplayMode" ]
      },
      "default": {}
    },
    "ContentPermissionStore": {
      "type": "object",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "userGroupName": {
            "type": "string"
          },
          "contentPermissions": {
            "$ref": "#/definitions/contentPermissionItemList"
          }
        },
        "required": [ "userGroupName", "contentPermissions" ]
      }
    },
    "DataSourcesStorage": {
      "type": "object",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "SourceID": {
            "type": "string"
          },
          "Layout": {
            "type": "string"
          },
          "StreamSystemID": {
            "type": "string"
          },
          "Topic": {
            "type": "string"
          },
          "StreamTopic": {
            "type": "string"
          },
          "Broker": {
            "type": "string"
          },
          "BrokerPort": {
            "type": "integer"
          },
          "UserID": {
            "type": "string"
          },
          "PasswordCrypted": {
            "type": "string"
          },
          "WithCertificates": {
            "type": "boolean"
          },
          "CA_CertificateName": {
            "type": "string"
          },
          "CA_Certificate": {
            "type": "string",
            "format": "certificate"
          },
          "Cert_CertificateName": {
            "type": "string"
          },
          "Cert_Certificate": {
            "type": "string",
            "format": "certificate"
          },
          "Key_CertificateName": {
            "type": "string"
          },
          "Key_Certificate": {
            "type": "string",
            "format": "base64"
          },
          "Key_PwdCrypted": {
            "type": "string"
          },
          "CycleTime": {
            "type": "integer"
          }
        },
        "required": [ "SourceID", "StreamSystemID", "Topic", "StreamTopic", "Broker", "BrokerPort", "Layout" ]
      }
    },
    "InteractiveChartStorage": {
      "type": "object",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "ChartID": {
            "type": "string"
          },
          "ChartProperties": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "description": "YT-Chart-Options",
                  "properties": {
                    "ChartType": {
                      "type": "integer"
                    },
                    "AxisDescription": {
                      "$ref": "#/definitions/axisList"
                    },
                    "UseHoverEffect": {
                      "type": "boolean"
                    },
                    "ShowDifferentials": {
                      "type": "boolean"
                    },
                    "FillMode": {
                      "type": "string"
                    },
                    "IsYTChart": {
                      "type": "boolean"
                    }
                  },
                  "required": [ "AxisDescription", "UseHoverEffect", "ChartType", "FillMode", "IsYTChart" ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "description": "Bar-Chart-Options",
                  "properties": {
                    "ChartType": {
                      "type": "integer"
                    },
                    "AxisDescription": {
                      "$ref": "#/definitions/axisList"
                    },
                    "UseHoverEffect": {
                      "type": "boolean"
                    },
                    "ShowDifferentials": {
                      "type": "boolean"
                    },
                    "IsBarChart": {
                      "type": "boolean"
                    }
                  },
                  "required": [ "AxisDescription", "ChartType", "UseHoverEffect", "IsBarChart" ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "description": "Pie-Chart-Options",
                  "properties": {
                    "ChartType": {
                      "type": "integer"
                    },
                    "AxisDescription": {
                      "$ref": "#/definitions/axisList"
                    },
                    "UseHoverEffect": {
                      "type": "boolean"
                    },
                    "ShowDifferentials": {
                      "type": "boolean"
                    },
                    "IsPieChart": {
                      "type": "boolean"
                    }
                  },
                  "required": [ "ChartType", "UseHoverEffect", "IsPieChart" ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "description": "Ring-Chart-Options",
                  "properties": {
                    "ChartType": {
                      "type": "integer"
                    },
                    "AxisDescription": {
                      "$ref": "#/definitions/axisList"
                    },
                    "UseHoverEffect": {
                      "type": "boolean"
                    },
                    "ShowDifferentials": {
                      "type": "boolean"
                    },
                    "IsRingChart": {
                      "type": "boolean"
                    }
                  },
                  "required": [ "ChartType", "UseHoverEffect", "IsRingChart" ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "description": "Compare-YT-Chart-Options",
                  "properties": {
                    "ChartType": {
                      "type": "integer"
                    },
                    "AxisDescription": {
                      "$ref": "#/definitions/axisList"
                    },
                    "UseHoverEffect": {
                      "type": "boolean"
                    },
                    "ShowDifferentials": {
                      "type": "boolean"
                    },
                    "FillMode": {
                      "type": "string"
                    },
                    "CompareInterval": {
                      "$ref": "#/definitions/timeIntervalOptions"
                    },
                    "CompareType": {
                      "type": "string"
                    },
                    "IsCompareYTChart": {
                      "type": "boolean"
                    }
                  },
                  "required": [ "AxisDescription", "ChartType", "UseHoverEffect", "FillMode", "CompareInterval", "CompareType", "IsCompareYTChart" ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "description": "Time-Series-Bar-Chart-Options",
                  "properties": {
                    "ChartType": {
                      "type": "integer"
                    },
                    "AxisDescription": {
                      "$ref": "#/definitions/axisList"
                    },
                    "UseHoverEffect": {
                      "type": "boolean"
                    },
                    "ShowDifferentials": {
                      "type": "boolean"
                    },
                    "CompareInterval": {
                      "$ref": "#/definitions/timeIntervalOptions"
                    },
                    "CompareType": {
                      "type": "string"
                    },
                    "IsTimeSeriesBarChart": {
                      "type": "boolean"
                    },
                    "BarIntervalWidth": {
                      "$ref": "#/definitions/timeIntervalOptions"
                    }
                  },
                  "required": [ "AxisDescription", "ChartType", "UseHoverEffect", "CompareInterval", "CompareType", "IsTimeSeriesBarChart", "BarIntervalWidth" ],
                  "additionalProperties": false
                }
              ]
            }
          },
          "Data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "From": {
                  "type": "string"
                },
                "To": {
                  "type": "string"
                },
                "IsVisible": {
                  "type": "boolean"
                },
                "Channels": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "Name": {
                        "type": "string"
                      },
                      "SourceID": {
                        "type": "string"
                      },
                      "Datatype": {
                        "type": "string"
                      },
                      "VarColor": {
                        "type": "string"
                      },
                      "IsVisible": {
                        "type": "boolean"
                      },
                      "Unit": {
                        "type": "string"
                      },
                      "CustomUnit": {
                        "type": "string"
                      },
                      "UserFalseAlias": {
                        "type": "string"
                      },
                      "UserTrueAlias": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "RefreshInterval": {
            "$ref": "#/definitions/timeIntervalOptions"
          }
        },
        "additionalProperties": false,
        "required": [ "ChartID", "ChartProperties", "Data", "RefreshInterval" ]
      }
    }
  },
  "required": [ "KeyValueStore", "LayoutStore", "UserLayoutStore", "ContentPermissionStore", "DataSourcesStorage", "InteractiveChartStorage" ]
}

=== jay417jay/AnalyticsTest/AnalyticsHMIProject/Server/TcHmiAnalytics/TcHmiAnalytics.Config.default.json
{
    "ContentPermissionStore": {},
    "DataSourcesStorage": {},
    "InteractiveChartStorage": {},
    "KeyValueStore": {},
    "LayoutPropertiesKeyValueStore": {
        "__SystemAdministrator__Network_1__Network_LayoutManager": {
            "keyValueEntries": [
                {
                    "key": "PieChartNameAlias",
                    "value": "Product Type"
                },
                {
                    "key": "PieChartFontsizeTitle",
                    "value": "25"
                },
                {
                    "key": "ThresholdClassifier1ChNameAlias",
                    "value": "OEE Alarm"
                },
                {
                    "key": "ThresholdClassifier1ChShowMilliSeconds",
                    "value": "false"
                }
            ],
            "layoutID": "__SystemAdministrator__Network_1__Network_LayoutManager"
        }
    },
    "LayoutStore": {
        "__SystemAdministrator__Network_1__Network_LayoutManager__0": {
            "InteractiveControls": [],
            "LayoutHash": [],
            "LayoutID": "__SystemAdministrator__Network_1__Network_LayoutManager__0",
            "LayoutValue": []
        },
        "__SystemAdministrator__Network_1__Network_LayoutManager__2": {
            "InteractiveControls": [],
            "LayoutHash": [
                {
                    "CType": "TcHmi.Controls.Analytics.OEE",
                    "Cnt": 1
                },
                {
                    "CType": "TcHmi.Controls.Analytics.PieChart",
                    "Cnt": 1
                },
                {
                    "CType": "TcHmi.Controls.Analytics.TrafficLight",
                    "Cnt": 1
                },
                {
                    "CType": "TcHmi.Controls.Analytics.Process",
                    "Cnt": 1
                },
                {
                    "CType": "",
                    "Cnt": 1
                }
            ],
            "LayoutID": "__SystemAdministrator__Network_1__Network_LayoutManager__2",
            "LayoutValue": [
                {
                    "cE": 11,
                    "cS": 2,
                    "id": "PackMLOverallEquipmentEffectivenessOEE_GridElement",
                    "rE": 7,
                    "rS": 1,
                    "vis": true
                },
                {
                    "cE": 23,
                    "cS": 11,
                    "id": "PieChart_GridElement",
                    "rE": 9,
                    "rS": 1,
                    "vis": true
                },
                {
                    "cE": 6,
                    "cS": 2,
                    "id": "ThresholdClassifier1Ch_GridElement",
                    "rE": 16,
                    "rS": 7,
                    "vis": true
                },
                {
                    "cE": 23,
                    "cS": 6,
                    "id": "PreventiveMaintenanceLifetimeAnalysis_GridElement",
                    "rE": 16,
                    "rS": 9,
                    "vis": true
                },
                {
                    "cE": 23,
                    "cS": 11,
                    "id": "grid-buffer-cell-id",
                    "rE": 9,
                    "rS": 1,
                    "vis": false
                }
            ]
        }
    },
    "UserLayoutStore": {
        "__SystemAdministrator__Network_1__Network_LayoutManager__0": {
            "ContentID": "Network_1",
            "DisplayMode": "SMARTPHONE",
            "LayoutID": "__SystemAdministrator__Network_1__Network_LayoutManager__0",
            "UserID": "__SystemAdministrator",
            "UserLayoutID": "__SystemAdministrator__Network_1__Network_LayoutManager__0"
        },
        "__SystemAdministrator__Network_1__Network_LayoutManager__2": {
            "ContentID": "Network_1",
            "DisplayMode": "MONITOR",
            "LayoutID": "__SystemAdministrator__Network_1__Network_LayoutManager__2",
            "UserID": "__SystemAdministrator",
            "UserLayoutID": "__SystemAdministrator__Network_1__Network_LayoutManager__2"
        }
    }
}
